config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  # def show
  # end

  def new
    @flat = Flat.new
  end

  # def create
  # end

  # def update
  # end

  # def edit
  # end

  # def destroy
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flat_helper.rb
module FlatHelper
end

app/views/flats/create.html.erb
<h1>Flat#create</h1>
<p>Find me in app/views/flat/create.html.erb</p>

app/views/flats/destroy.html.erb
<h1>Flat#destroy</h1>
<p>Find me in app/views/flat/destroy.html.erb</p>

app/views/flats/edit.html.erb
<h1>Flat#edit</h1>
<p>Find me in app/views/flat/edit.html.erb</p>

app/views/flats/index.html.erb
<div class="navbar" class="border-bottom"> 
  <h3> Simple Airbnb </h3>
  <%= link_to "Add flat", new_flat_path, :class => "btn btn-outline-primary" %>
</div>


<h1> All our Flats (<%= Flat.count %>) </h1>
<div class="row">
    <% @flats.each do |flat| %>
        <div class="col-sm-6">
            <div class= "card"> 
                <div class="card-header">
                    <h2 class="card-title"><%= flat.name %></h2>
                </div>
                <div class="card-body">
                    <p class="card-text"> 
                        <%= flat.description %>
                        <%= flat.address %> 
                    </p>
                    <p class="card-details">
                        <%= flat.price_per_night %>
                        <%= flat.number_of_guests %>
                    </p>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/flats/new.html.erb
<h1>Flat#new</h1>
<p>Find me in app/views/flat/new.html.erb</p>

app/views/flats/show.html.erb
<h1>Flat#show</h1>
<p>Find me in app/views/flat/show.html.erb</p>

app/views/flats/update.html.erb
<h1>Flat#update</h1>
<p>Find me in app/views/flat/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>